name: EntityFrameworkCore.Batch nuget push

on:
  push:
    branches:
      - '*'  
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.0.x

    - name: Build
      working-directory: ../
      run: dotnet build --configuration Release

    - name: Produce nuget pack for EntityFrameworkCore.Batch
      run: dotnet pack Sanatana.EntityFrameworkCore.Batch/Sanatana.EntityFrameworkCore.Batch.csproj -o ../nuget -c Release -v n

    - name: Produce nuget pack for EntityFrameworkCore.Batch.PostgreSql
      run: dotnet pack Sanatana.EntityFrameworkCore.Batch.PostgreSql/Sanatana.EntityFrameworkCore.Batch.PostgreSql.csproj -o ../nuget -c Release -v n
 
    - name: Produce nuget pack for EntityFrameworkCore.Batch.SqlServer
      run: dotnet pack Sanatana.EntityFrameworkCore.Batch.SqlServer/Sanatana.EntityFrameworkCore.Batch.SqlServer.csproj -o ../nuget -c Release -v n
 
    - name: Publish all nuget packages
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push nuget/Sanatana.EntityFrameworkCore.Batch.*.nupkg --force-english-output -k $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
